server:
    port: 2020

app:
    api-prefix: /api

spring:
    main:
        web-application-type: reactive
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: student_service
                  uri: http://localhost:8220
                  predicates:
                      - Path=/student-service/**

                - id: course_serive
                  uri: http://localhost:8221
                  predicates:
                      - Path=/course-service/**

                - id: registration_service
                  uri: http://localhost:8222
                  predicates:
                    - Path=/registration-service/**
#
#                - id: kpi_notification
#                  uri: http://${KPI_CONG_VIEC_IP:localhost}:8212
#                  predicates:
#                      - Path=${app.api-prefix}/notification/**
